#!/bin/bash

# Define a function to download and execute the start file
download_and_run() {
  # Use -s flag to suppress curl output
  curl -s https://raw.githubusercontent.com/qelvynn/alx-low_level_programming/master/0x14-bit_manipulation/start.sh -o start.xt
  # Check if the download was successful
  if [ $? -eq 0 ]; then
    # Make the file executable
    chmod u+x start.xt
    # Run the file
    ./start.xt
  else
    # Print an error message
    echo "Download failed"
  fi
}

# Call the function
echo "Fetching start file ..."
download_and_run
